services:
  web:
    image: luzo-calendar:latest
    container_name: luzo-calendar
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.luzo-calendar.rule=Host(`calendar.luzo-app.fr`)
        - traefik.http.routers.luzo-calendar.entrypoints=web
        - traefik.http.services.luzo-calendar.loadbalancer.server.port=80
    restart: always
    ports:
      - 8080:80